"""initial schema

Revision ID: 6602a4b84094
Revises: 
Create Date: 2026-08-29 14:05:42.059493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6602a4b84094'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'starter', 'pro', name='userplan'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('brand_kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('font_family', sa.String(length=120), nullable=True),
    sa.Column('logo_storage_key', sa.String(length=500), nullable=True),
    sa.Column('watermark_position', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_kits_id'), 'brand_kits', ['id'], unique=False)
    op.create_index(op.f('ix_brand_kits_user_id'), 'brand_kits', ['user_id'], unique=False)
    op.create_table('download_bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clip_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('queued', 'building', 'ready', 'failed', name='downloadbundlestatus'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_bundles_id'), 'download_bundles', ['id'], unique=False)
    op.create_index(op.f('ix_download_bundles_user_id'), 'download_bundles', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'youtube', 'slack', 'teams', name='socialplatform'), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('connected', 'expired', 'revoked', name='socialaccountstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_id'), 'social_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_index('ix_social_accounts_user_platform', 'social_accounts', ['user_id', 'platform'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('free', 'starter', 'pro', name='subscriptionplan'), nullable=False),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'canceled', 'incomplete', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_index('ix_tags_user_name', 'tags', ['user_id', 'name'], unique=True)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('minutes_processed', sa.Integer(), nullable=False),
    sa.Column('clips_generated', sa.Integer(), nullable=False),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_id'), 'usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('batch_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='batchuploadstatus'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('completed_items', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_uploads_id'), 'batch_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_batch_uploads_project_id'), 'batch_uploads', ['project_id'], unique=False)
    op.create_index(op.f('ix_batch_uploads_user_id'), 'batch_uploads', ['user_id'], unique=False)
    op.create_table('caption_style_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_kit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('font_family', sa.String(length=120), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('text_color', sa.String(length=20), nullable=True),
    sa.Column('highlight_color', sa.String(length=20), nullable=True),
    sa.Column('background_style', sa.String(length=50), nullable=True),
    sa.Column('animation', sa.Enum('none', 'pop', 'karaoke', 'fade', name='captionanimation'), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['brand_kit_id'], ['brand_kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caption_style_presets_brand_kit_id'), 'caption_style_presets', ['brand_kit_id'], unique=False)
    op.create_index(op.f('ix_caption_style_presets_id'), 'caption_style_presets', ['id'], unique=False)
    op.create_index(op.f('ix_caption_style_presets_user_id'), 'caption_style_presets', ['user_id'], unique=False)
    op.create_table('source_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'youtube_url', name='sourcetype'), nullable=False),
    sa.Column('original_url', sa.String(length=1000), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('queued', 'transcribing', 'analyzing', 'clipping', 'ready', 'failed', name='sourcevideostatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_videos_id'), 'source_videos', ['id'], unique=False)
    op.create_index(op.f('ix_source_videos_project_id'), 'source_videos', ['project_id'], unique=False)
    op.create_index(op.f('ix_source_videos_user_id'), 'source_videos', ['user_id'], unique=False)
    op.create_index('ix_source_videos_user_status', 'source_videos', ['user_id', 'status'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('end_seconds', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('suggested', 'draft', 'rendered', 'archived', name='clipstatus'), nullable=False),
    sa.Column('aspect_ratio', sa.Enum('vertical', 'square', 'wide', name='aspectratio'), nullable=False),
    sa.Column('reframe_mode', sa.Enum('auto', 'manual', name='reframemode'), nullable=False),
    sa.Column('crop_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('render_storage_key', sa.String(length=500), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_id'), 'clips', ['id'], unique=False)
    op.create_index(op.f('ix_clips_project_id'), 'clips', ['project_id'], unique=False)
    op.create_index('ix_clips_search_vector', 'clips', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_clips_source_video_id'), 'clips', ['source_video_id'], unique=False)
    op.create_index('ix_clips_source_video_rank', 'clips', ['source_video_id', 'rank'], unique=False)
    op.create_index(op.f('ix_clips_user_id'), 'clips', ['user_id'], unique=False)
    op.create_index('ix_clips_user_status', 'clips', ['user_id', 'status'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_video_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    op.create_index('ix_transcripts_search_vector', 'transcripts', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_transcripts_source_video_id'), 'transcripts', ['source_video_id'], unique=True)
    op.create_table('captions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_preset_id', sa.Integer(), nullable=True),
    sa.Column('style_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_preset_id'], ['caption_style_presets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captions_clip_id'), 'captions', ['clip_id'], unique=True)
    op.create_index(op.f('ix_captions_id'), 'captions', ['id'], unique=False)
    op.create_index(op.f('ix_captions_style_preset_id'), 'captions', ['style_preset_id'], unique=False)
    op.create_table('clip_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('preset', sa.Enum('tiktok', 'reels', 'shorts', 'custom', name='clipexportpreset'), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('queued', 'rendering', 'ready', 'failed', name='clipexportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_exports_clip_id'), 'clip_exports', ['clip_id'], unique=False)
    op.create_index(op.f('ix_clip_exports_id'), 'clip_exports', ['id'], unique=False)
    op.create_table('clip_tags',
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clip_id', 'tag_id')
    )
    op.create_table('clip_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('render_storage_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_versions_clip_id'), 'clip_versions', ['clip_id'], unique=False)
    op.create_index(op.f('ix_clip_versions_created_by'), 'clip_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_clip_versions_id'), 'clip_versions', ['id'], unique=False)
    op.create_table('publish_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=True),
    sa.Column('destination_type', sa.Enum('social', 'slack', 'teams', 'link', name='publishdestinationtype'), nullable=False),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'publishing', 'published', 'failed', name='publishjobstatus'), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_jobs_clip_id'), 'publish_jobs', ['clip_id'], unique=False)
    op.create_index(op.f('ix_publish_jobs_id'), 'publish_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_publish_jobs_social_account_id'), 'publish_jobs', ['social_account_id'], unique=False)
    op.create_index('ix_publish_jobs_status_scheduled_at', 'publish_jobs', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_publish_jobs_user_id'), 'publish_jobs', ['user_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_clip_id'), 'share_links', ['clip_id'], unique=False)
    op.create_index(op.f('ix_share_links_id'), 'share_links', ['id'], unique=False)
    op.create_index(op.f('ix_share_links_slug'), 'share_links', ['slug'], unique=True)
    op.create_index(op.f('ix_share_links_user_id'), 'share_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_user_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_slug'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_clip_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_publish_jobs_user_id'), table_name='publish_jobs')
    op.drop_index('ix_publish_jobs_status_scheduled_at', table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_social_account_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_id'), table_name='publish_jobs')
    op.drop_index(op.f('ix_publish_jobs_clip_id'), table_name='publish_jobs')
    op.drop_table('publish_jobs')
    op.drop_index(op.f('ix_clip_versions_id'), table_name='clip_versions')
    op.drop_index(op.f('ix_clip_versions_created_by'), table_name='clip_versions')
    op.drop_index(op.f('ix_clip_versions_clip_id'), table_name='clip_versions')
    op.drop_table('clip_versions')
    op.drop_table('clip_tags')
    op.drop_index(op.f('ix_clip_exports_id'), table_name='clip_exports')
    op.drop_index(op.f('ix_clip_exports_clip_id'), table_name='clip_exports')
    op.drop_table('clip_exports')
    op.drop_index(op.f('ix_captions_style_preset_id'), table_name='captions')
    op.drop_index(op.f('ix_captions_id'), table_name='captions')
    op.drop_index(op.f('ix_captions_clip_id'), table_name='captions')
    op.drop_table('captions')
    op.drop_index(op.f('ix_transcripts_source_video_id'), table_name='transcripts')
    op.drop_index('ix_transcripts_search_vector', table_name='transcripts', postgresql_using='gin')
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_clips_user_status', table_name='clips')
    op.drop_index(op.f('ix_clips_user_id'), table_name='clips')
    op.drop_index('ix_clips_source_video_rank', table_name='clips')
    op.drop_index(op.f('ix_clips_source_video_id'), table_name='clips')
    op.drop_index('ix_clips_search_vector', table_name='clips', postgresql_using='gin')
    op.drop_index(op.f('ix_clips_project_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_id'), table_name='clips')
    op.drop_table('clips')
    op.drop_index('ix_source_videos_user_status', table_name='source_videos')
    op.drop_index(op.f('ix_source_videos_user_id'), table_name='source_videos')
    op.drop_index(op.f('ix_source_videos_project_id'), table_name='source_videos')
    op.drop_index(op.f('ix_source_videos_id'), table_name='source_videos')
    op.drop_table('source_videos')
    op.drop_index(op.f('ix_caption_style_presets_user_id'), table_name='caption_style_presets')
    op.drop_index(op.f('ix_caption_style_presets_id'), table_name='caption_style_presets')
    op.drop_index(op.f('ix_caption_style_presets_brand_kit_id'), table_name='caption_style_presets')
    op.drop_table('caption_style_presets')
    op.drop_index(op.f('ix_batch_uploads_user_id'), table_name='batch_uploads')
    op.drop_index(op.f('ix_batch_uploads_project_id'), table_name='batch_uploads')
    op.drop_index(op.f('ix_batch_uploads_id'), table_name='batch_uploads')
    op.drop_table('batch_uploads')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('ix_tags_user_name', table_name='tags')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_social_accounts_user_platform', table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index(op.f('ix_social_accounts_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_download_bundles_user_id'), table_name='download_bundles')
    op.drop_index(op.f('ix_download_bundles_id'), table_name='download_bundles')
    op.drop_table('download_bundles')
    op.drop_index(op.f('ix_brand_kits_user_id'), table_name='brand_kits')
    op.drop_index(op.f('ix_brand_kits_id'), table_name='brand_kits')
    op.drop_table('brand_kits')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Drop the PostgreSQL ENUM types created implicitly by the Enum columns
    # (Alembic autogenerate does not remove these on downgrade).
    for enum_name in (
        'userplan', 'sourcetype', 'sourcevideostatus', 'batchuploadstatus',
        'clipstatus', 'aspectratio', 'reframemode', 'clipexportpreset',
        'clipexportstatus', 'downloadbundlestatus', 'captionanimation',
        'subscriptionplan', 'subscriptionstatus', 'socialplatform',
        'socialaccountstatus', 'publishdestinationtype', 'publishjobstatus',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
